// Code generated by MockGen. DO NOT EDIT.
// Source: internal/features/user/usecase/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/features/user/usecase/usecase.go -destination=internal/features/user/usecase/mock_usecase_test.go -package=userusecase_test
//

// Package userusecase_test is a generated GoMock package.
package userusecase_test

import (
	context "context"
	reflect "reflect"
	time "time"

	corejwt "github.com/egotk/golang-advert-app/internal/core/jwt"
	userentity "github.com/egotk/golang-advert-app/internal/features/user/entity"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
	isgomock struct{}
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// CreateRefreshToken mocks base method.
func (m *Mockrepo) CreateRefreshToken(ctx context.Context, token userentity.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockrepoMockRecorder) CreateRefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*Mockrepo)(nil).CreateRefreshToken), ctx, token)
}

// CreateUser mocks base method.
func (m *Mockrepo) CreateUser(ctx context.Context, user *userentity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockrepoMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*Mockrepo)(nil).CreateUser), ctx, user)
}

// DeleteRefreshTokenByHash mocks base method.
func (m *Mockrepo) DeleteRefreshTokenByHash(ctx context.Context, userId int64, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshTokenByHash", ctx, userId, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshTokenByHash indicates an expected call of DeleteRefreshTokenByHash.
func (mr *MockrepoMockRecorder) DeleteRefreshTokenByHash(ctx, userId, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshTokenByHash", reflect.TypeOf((*Mockrepo)(nil).DeleteRefreshTokenByHash), ctx, userId, hash)
}

// GetRefreshTokenByHash mocks base method.
func (m *Mockrepo) GetRefreshTokenByHash(ctx context.Context, hash string) (userentity.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenByHash", ctx, hash)
	ret0, _ := ret[0].(userentity.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshTokenByHash indicates an expected call of GetRefreshTokenByHash.
func (mr *MockrepoMockRecorder) GetRefreshTokenByHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenByHash", reflect.TypeOf((*Mockrepo)(nil).GetRefreshTokenByHash), ctx, hash)
}

// GetUserByEmail mocks base method.
func (m *Mockrepo) GetUserByEmail(ctx context.Context, email string) (userentity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(userentity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockrepoMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*Mockrepo)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *Mockrepo) GetUserByID(ctx context.Context, id int64) (userentity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(userentity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockrepoMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*Mockrepo)(nil).GetUserByID), ctx, id)
}

// IncrementFailedLoginCount mocks base method.
func (m *Mockrepo) IncrementFailedLoginCount(ctx context.Context, id, version int64) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementFailedLoginCount", ctx, id, version)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementFailedLoginCount indicates an expected call of IncrementFailedLoginCount.
func (mr *MockrepoMockRecorder) IncrementFailedLoginCount(ctx, id, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementFailedLoginCount", reflect.TypeOf((*Mockrepo)(nil).IncrementFailedLoginCount), ctx, id, version)
}

// ListUsers mocks base method.
func (m *Mockrepo) ListUsers(ctx context.Context, limit, offset *int64) ([]userentity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, limit, offset)
	ret0, _ := ret[0].([]userentity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockrepoMockRecorder) ListUsers(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*Mockrepo)(nil).ListUsers), ctx, limit, offset)
}

// ReissueRefreshToken mocks base method.
func (m *Mockrepo) ReissueRefreshToken(ctx context.Context, userID int64, oldHash string, newToken userentity.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReissueRefreshToken", ctx, userID, oldHash, newToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReissueRefreshToken indicates an expected call of ReissueRefreshToken.
func (mr *MockrepoMockRecorder) ReissueRefreshToken(ctx, userID, oldHash, newToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReissueRefreshToken", reflect.TypeOf((*Mockrepo)(nil).ReissueRefreshToken), ctx, userID, oldHash, newToken)
}

// ResetFailedLoginCount mocks base method.
func (m *Mockrepo) ResetFailedLoginCount(ctx context.Context, id, version int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetFailedLoginCount", ctx, id, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetFailedLoginCount indicates an expected call of ResetFailedLoginCount.
func (mr *MockrepoMockRecorder) ResetFailedLoginCount(ctx, id, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetFailedLoginCount", reflect.TypeOf((*Mockrepo)(nil).ResetFailedLoginCount), ctx, id, version)
}

// MockjwtService is a mock of jwtService interface.
type MockjwtService struct {
	ctrl     *gomock.Controller
	recorder *MockjwtServiceMockRecorder
	isgomock struct{}
}

// MockjwtServiceMockRecorder is the mock recorder for MockjwtService.
type MockjwtServiceMockRecorder struct {
	mock *MockjwtService
}

// NewMockjwtService creates a new mock instance.
func NewMockjwtService(ctrl *gomock.Controller) *MockjwtService {
	mock := &MockjwtService{ctrl: ctrl}
	mock.recorder = &MockjwtServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockjwtService) EXPECT() *MockjwtServiceMockRecorder {
	return m.recorder
}

// IssuePair mocks base method.
func (m *MockjwtService) IssuePair(role string, userId int64) (corejwt.Pair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssuePair", role, userId)
	ret0, _ := ret[0].(corejwt.Pair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssuePair indicates an expected call of IssuePair.
func (mr *MockjwtServiceMockRecorder) IssuePair(role, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssuePair", reflect.TypeOf((*MockjwtService)(nil).IssuePair), role, userId)
}
