// Code generated by MockGen. DO NOT EDIT.
// Source: internal/features/user/controller/rest/controller.go
//
// Generated by this command:
//
//	mockgen -source=internal/features/user/controller/rest/controller.go -destination=internal/features/user/controller/rest/mock_usecase_test.go -package=userhttp_test
//

// Package userhttp_test is a generated GoMock package.
package userhttp_test

import (
	context "context"
	reflect "reflect"

	userentity "github.com/egotk/golang-advert-app/internal/features/user/entity"
	userusecase "github.com/egotk/golang-advert-app/internal/features/user/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockuseCase is a mock of useCase interface.
type MockuseCase struct {
	ctrl     *gomock.Controller
	recorder *MockuseCaseMockRecorder
	isgomock struct{}
}

// MockuseCaseMockRecorder is the mock recorder for MockuseCase.
type MockuseCaseMockRecorder struct {
	mock *MockuseCase
}

// NewMockuseCase creates a new mock instance.
func NewMockuseCase(ctrl *gomock.Controller) *MockuseCase {
	mock := &MockuseCase{ctrl: ctrl}
	mock.recorder = &MockuseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuseCase) EXPECT() *MockuseCaseMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockuseCase) CreateUser(ctx context.Context, dto userusecase.CreateDTO) (userentity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, dto)
	ret0, _ := ret[0].(userentity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockuseCaseMockRecorder) CreateUser(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockuseCase)(nil).CreateUser), ctx, dto)
}

// GetUserByID mocks base method.
func (m *MockuseCase) GetUserByID(ctx context.Context, id int64) (userentity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(userentity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockuseCaseMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockuseCase)(nil).GetUserByID), ctx, id)
}

// ListUsers mocks base method.
func (m *MockuseCase) ListUsers(ctx context.Context, limit, offset *int64) ([]userentity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, limit, offset)
	ret0, _ := ret[0].([]userentity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockuseCaseMockRecorder) ListUsers(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockuseCase)(nil).ListUsers), ctx, limit, offset)
}

// Login mocks base method.
func (m *MockuseCase) Login(ctx context.Context, dto userusecase.LoginDTO) (userusecase.LoginResultDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, dto)
	ret0, _ := ret[0].(userusecase.LoginResultDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockuseCaseMockRecorder) Login(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockuseCase)(nil).Login), ctx, dto)
}

// Logout mocks base method.
func (m *MockuseCase) Logout(ctx context.Context, dto userusecase.LogoutDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockuseCaseMockRecorder) Logout(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockuseCase)(nil).Logout), ctx, dto)
}

// RefreshTokens mocks base method.
func (m *MockuseCase) RefreshTokens(ctx context.Context, dto userusecase.RefreshTokensDTO) (userusecase.TokensDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokens", ctx, dto)
	ret0, _ := ret[0].(userusecase.TokensDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshTokens indicates an expected call of RefreshTokens.
func (mr *MockuseCaseMockRecorder) RefreshTokens(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokens", reflect.TypeOf((*MockuseCase)(nil).RefreshTokens), ctx, dto)
}
