// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go
//
// Generated by this command:
//
//	mockgen -source=controller.go -destination=mock_usecase_test.go -package=favrest_test
//

// Package favrest_test is a generated GoMock package.
package favrest_test

import (
	context "context"
	reflect "reflect"

	favusecase "github.com/egotk/golang-advert-app/internal/features/favourite/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockuseCase is a mock of useCase interface.
type MockuseCase struct {
	ctrl     *gomock.Controller
	recorder *MockuseCaseMockRecorder
	isgomock struct{}
}

// MockuseCaseMockRecorder is the mock recorder for MockuseCase.
type MockuseCaseMockRecorder struct {
	mock *MockuseCase
}

// NewMockuseCase creates a new mock instance.
func NewMockuseCase(ctrl *gomock.Controller) *MockuseCase {
	mock := &MockuseCase{ctrl: ctrl}
	mock.recorder = &MockuseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuseCase) EXPECT() *MockuseCaseMockRecorder {
	return m.recorder
}

// ListIDs mocks base method.
func (m *MockuseCase) ListIDs(ctx context.Context, userID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIDs", ctx, userID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIDs indicates an expected call of ListIDs.
func (mr *MockuseCaseMockRecorder) ListIDs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIDs", reflect.TypeOf((*MockuseCase)(nil).ListIDs), ctx, userID)
}

// Remove mocks base method.
func (m *MockuseCase) Remove(ctx context.Context, dto favusecase.RemoveDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockuseCaseMockRecorder) Remove(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockuseCase)(nil).Remove), ctx, dto)
}
