// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mock_usecase_test.go -package=advertusecase_test
//

// Package advertusecase_test is a generated GoMock package.
package advertusecase_test

import (
	context "context"
	io "io"
	reflect "reflect"

	advertentity "github.com/egotk/golang-advert-app/internal/features/advert/entity"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
	isgomock struct{}
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// ChangeStatus mocks base method.
func (m *Mockrepo) ChangeStatus(ctx context.Context, id int64, oldStatus, newStatus advertentity.Status) (advertentity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeStatus", ctx, id, oldStatus, newStatus)
	ret0, _ := ret[0].(advertentity.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeStatus indicates an expected call of ChangeStatus.
func (mr *MockrepoMockRecorder) ChangeStatus(ctx, id, oldStatus, newStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeStatus", reflect.TypeOf((*Mockrepo)(nil).ChangeStatus), ctx, id, oldStatus, newStatus)
}

// Count mocks base method.
func (m *Mockrepo) Count(ctx context.Context, filter advertentity.Filter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockrepoMockRecorder) Count(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*Mockrepo)(nil).Count), ctx, filter)
}

// CountFavourites mocks base method.
func (m *Mockrepo) CountFavourites(ctx context.Context, userID int64, filter advertentity.Filter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFavourites", ctx, userID, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFavourites indicates an expected call of CountFavourites.
func (mr *MockrepoMockRecorder) CountFavourites(ctx, userID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFavourites", reflect.TypeOf((*Mockrepo)(nil).CountFavourites), ctx, userID, filter)
}

// Create mocks base method.
func (m *Mockrepo) Create(ctx context.Context, advert *advertentity.Advert) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, advert)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockrepoMockRecorder) Create(ctx, advert any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mockrepo)(nil).Create), ctx, advert)
}

// CreateImages mocks base method.
func (m *Mockrepo) CreateImages(ctx context.Context, advertID int64, images []advertentity.AdvertImage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateImages", ctx, advertID, images)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateImages indicates an expected call of CreateImages.
func (mr *MockrepoMockRecorder) CreateImages(ctx, advertID, images any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateImages", reflect.TypeOf((*Mockrepo)(nil).CreateImages), ctx, advertID, images)
}

// DeleteByID mocks base method.
func (m *Mockrepo) DeleteByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockrepoMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*Mockrepo)(nil).DeleteByID), ctx, id)
}

// DeleteImageByID mocks base method.
func (m *Mockrepo) DeleteImageByID(ctx context.Context, advertID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImageByID", ctx, advertID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImageByID indicates an expected call of DeleteImageByID.
func (mr *MockrepoMockRecorder) DeleteImageByID(ctx, advertID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImageByID", reflect.TypeOf((*Mockrepo)(nil).DeleteImageByID), ctx, advertID)
}

// GetByID mocks base method.
func (m *Mockrepo) GetByID(ctx context.Context, id int64) (advertentity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(advertentity.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockrepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*Mockrepo)(nil).GetByID), ctx, id)
}

// GetImageByID mocks base method.
func (m *Mockrepo) GetImageByID(ctx context.Context, imageID int64) (int64, advertentity.AdvertImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImageByID", ctx, imageID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(advertentity.AdvertImage)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetImageByID indicates an expected call of GetImageByID.
func (mr *MockrepoMockRecorder) GetImageByID(ctx, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImageByID", reflect.TypeOf((*Mockrepo)(nil).GetImageByID), ctx, imageID)
}

// IncrementViewsCount mocks base method.
func (m *Mockrepo) IncrementViewsCount(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementViewsCount", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementViewsCount indicates an expected call of IncrementViewsCount.
func (mr *MockrepoMockRecorder) IncrementViewsCount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementViewsCount", reflect.TypeOf((*Mockrepo)(nil).IncrementViewsCount), ctx, id)
}

// List mocks base method.
func (m *Mockrepo) List(ctx context.Context, limit, offset *int64, filter advertentity.Filter) ([]advertentity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset, filter)
	ret0, _ := ret[0].([]advertentity.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockrepoMockRecorder) List(ctx, limit, offset, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*Mockrepo)(nil).List), ctx, limit, offset, filter)
}

// ListFavourites mocks base method.
func (m *Mockrepo) ListFavourites(ctx context.Context, userID int64, limit, offset *int64, filter advertentity.Filter) ([]advertentity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFavourites", ctx, userID, limit, offset, filter)
	ret0, _ := ret[0].([]advertentity.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFavourites indicates an expected call of ListFavourites.
func (mr *MockrepoMockRecorder) ListFavourites(ctx, userID, limit, offset, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFavourites", reflect.TypeOf((*Mockrepo)(nil).ListFavourites), ctx, userID, limit, offset, filter)
}

// ListImagesByAdvertID mocks base method.
func (m *Mockrepo) ListImagesByAdvertID(ctx context.Context, advertID int64) ([]advertentity.AdvertImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListImagesByAdvertID", ctx, advertID)
	ret0, _ := ret[0].([]advertentity.AdvertImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListImagesByAdvertID indicates an expected call of ListImagesByAdvertID.
func (mr *MockrepoMockRecorder) ListImagesByAdvertID(ctx, advertID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListImagesByAdvertID", reflect.TypeOf((*Mockrepo)(nil).ListImagesByAdvertID), ctx, advertID)
}

// ListImagesByAdvertIDs mocks base method.
func (m *Mockrepo) ListImagesByAdvertIDs(ctx context.Context, ids []int64) (map[int64][]advertentity.AdvertImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListImagesByAdvertIDs", ctx, ids)
	ret0, _ := ret[0].(map[int64][]advertentity.AdvertImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListImagesByAdvertIDs indicates an expected call of ListImagesByAdvertIDs.
func (mr *MockrepoMockRecorder) ListImagesByAdvertIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListImagesByAdvertIDs", reflect.TypeOf((*Mockrepo)(nil).ListImagesByAdvertIDs), ctx, ids)
}

// Patch mocks base method.
func (m *Mockrepo) Patch(ctx context.Context, advert *advertentity.Advert) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", ctx, advert)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockrepoMockRecorder) Patch(ctx, advert any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*Mockrepo)(nil).Patch), ctx, advert)
}

// MockfavRepo is a mock of favRepo interface.
type MockfavRepo struct {
	ctrl     *gomock.Controller
	recorder *MockfavRepoMockRecorder
	isgomock struct{}
}

// MockfavRepoMockRecorder is the mock recorder for MockfavRepo.
type MockfavRepoMockRecorder struct {
	mock *MockfavRepo
}

// NewMockfavRepo creates a new mock instance.
func NewMockfavRepo(ctrl *gomock.Controller) *MockfavRepo {
	mock := &MockfavRepo{ctrl: ctrl}
	mock.recorder = &MockfavRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfavRepo) EXPECT() *MockfavRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockfavRepo) Add(ctx context.Context, advertID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, advertID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockfavRepoMockRecorder) Add(ctx, advertID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockfavRepo)(nil).Add), ctx, advertID, userID)
}

// Mockstorage is a mock of storage interface.
type Mockstorage struct {
	ctrl     *gomock.Controller
	recorder *MockstorageMockRecorder
	isgomock struct{}
}

// MockstorageMockRecorder is the mock recorder for Mockstorage.
type MockstorageMockRecorder struct {
	mock *Mockstorage
}

// NewMockstorage creates a new mock instance.
func NewMockstorage(ctrl *gomock.Controller) *Mockstorage {
	mock := &Mockstorage{ctrl: ctrl}
	mock.recorder = &MockstorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockstorage) EXPECT() *MockstorageMockRecorder {
	return m.recorder
}

// DeleteByPath mocks base method.
func (m *Mockstorage) DeleteByPath(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByPath", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByPath indicates an expected call of DeleteByPath.
func (mr *MockstorageMockRecorder) DeleteByPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByPath", reflect.TypeOf((*Mockstorage)(nil).DeleteByPath), path)
}

// GetByPath mocks base method.
func (m *Mockstorage) GetByPath(path string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPath", path)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPath indicates an expected call of GetByPath.
func (mr *MockstorageMockRecorder) GetByPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPath", reflect.TypeOf((*Mockstorage)(nil).GetByPath), path)
}

// Save mocks base method.
func (m *Mockstorage) Save(extension string, reader io.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", extension, reader)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockstorageMockRecorder) Save(extension, reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*Mockstorage)(nil).Save), extension, reader)
}
