// Code generated by MockGen. DO NOT EDIT.
// Source: internal/features/category/controller/grpc/controller.go
//
// Generated by this command:
//
//	mockgen -source=internal/features/category/controller/grpc/controller.go -destination=internal/features/category/controller/grpc/mock_usecase_test.go -package=categorygrpc_test
//

// Package categorygrpc_test is a generated GoMock package.
package categorygrpc_test

import (
	context "context"
	reflect "reflect"

	categoryentity "github.com/egotk/golang-advert-app/internal/features/category/entity"
	categoryusecase "github.com/egotk/golang-advert-app/internal/features/category/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockuseCase is a mock of useCase interface.
type MockuseCase struct {
	ctrl     *gomock.Controller
	recorder *MockuseCaseMockRecorder
	isgomock struct{}
}

// MockuseCaseMockRecorder is the mock recorder for MockuseCase.
type MockuseCaseMockRecorder struct {
	mock *MockuseCase
}

// NewMockuseCase creates a new mock instance.
func NewMockuseCase(ctrl *gomock.Controller) *MockuseCase {
	mock := &MockuseCase{ctrl: ctrl}
	mock.recorder = &MockuseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuseCase) EXPECT() *MockuseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockuseCase) Create(ctx context.Context, dto categoryusecase.CreateDTO) (categoryentity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, dto)
	ret0, _ := ret[0].(categoryentity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockuseCaseMockRecorder) Create(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockuseCase)(nil).Create), ctx, dto)
}

// Delete mocks base method.
func (m *MockuseCase) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockuseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockuseCase)(nil).Delete), ctx, id)
}

// List mocks base method.
func (m *MockuseCase) List(ctx context.Context) ([]categoryentity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]categoryentity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockuseCaseMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockuseCase)(nil).List), ctx)
}

// Patch mocks base method.
func (m *MockuseCase) Patch(ctx context.Context, dto categoryusecase.PatchDTO) (categoryentity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", ctx, dto)
	ret0, _ := ret[0].(categoryentity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockuseCaseMockRecorder) Patch(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockuseCase)(nil).Patch), ctx, dto)
}
