// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go
//
// Generated by this command:
//
//	mockgen -source=controller.go -destination=mock_usecase_test.go -package=advertgrpc_test
//

// Package advertgrpc_test is a generated GoMock package.
package advertgrpc_test

import (
	context "context"
	io "io"
	reflect "reflect"

	advertentity "github.com/egotk/golang-advert-app/internal/features/advert/entity"
	advertusecase "github.com/egotk/golang-advert-app/internal/features/advert/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockuseCase is a mock of useCase interface.
type MockuseCase struct {
	ctrl     *gomock.Controller
	recorder *MockuseCaseMockRecorder
	isgomock struct{}
}

// MockuseCaseMockRecorder is the mock recorder for MockuseCase.
type MockuseCaseMockRecorder struct {
	mock *MockuseCase
}

// NewMockuseCase creates a new mock instance.
func NewMockuseCase(ctrl *gomock.Controller) *MockuseCase {
	mock := &MockuseCase{ctrl: ctrl}
	mock.recorder = &MockuseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuseCase) EXPECT() *MockuseCaseMockRecorder {
	return m.recorder
}

// AddToFavourites mocks base method.
func (m *MockuseCase) AddToFavourites(ctx context.Context, dto advertusecase.AddToFavouritesDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToFavourites", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToFavourites indicates an expected call of AddToFavourites.
func (mr *MockuseCaseMockRecorder) AddToFavourites(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToFavourites", reflect.TypeOf((*MockuseCase)(nil).AddToFavourites), ctx, dto)
}

// Approve mocks base method.
func (m *MockuseCase) Approve(ctx context.Context, id int64) (advertentity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", ctx, id)
	ret0, _ := ret[0].(advertentity.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Approve indicates an expected call of Approve.
func (mr *MockuseCaseMockRecorder) Approve(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockuseCase)(nil).Approve), ctx, id)
}

// Archive mocks base method.
func (m *MockuseCase) Archive(ctx context.Context, dto advertusecase.ArchiveDTO) (advertentity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Archive", ctx, dto)
	ret0, _ := ret[0].(advertentity.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Archive indicates an expected call of Archive.
func (mr *MockuseCaseMockRecorder) Archive(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Archive", reflect.TypeOf((*MockuseCase)(nil).Archive), ctx, dto)
}

// Count mocks base method.
func (m *MockuseCase) Count(ctx context.Context, dto advertusecase.CountDTO) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, dto)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockuseCaseMockRecorder) Count(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockuseCase)(nil).Count), ctx, dto)
}

// CountFavourites mocks base method.
func (m *MockuseCase) CountFavourites(ctx context.Context, dto advertusecase.CountDTO) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFavourites", ctx, dto)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFavourites indicates an expected call of CountFavourites.
func (mr *MockuseCaseMockRecorder) CountFavourites(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFavourites", reflect.TypeOf((*MockuseCase)(nil).CountFavourites), ctx, dto)
}

// Create mocks base method.
func (m *MockuseCase) Create(ctx context.Context, dto advertusecase.CreateDTO) (advertentity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, dto)
	ret0, _ := ret[0].(advertentity.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockuseCaseMockRecorder) Create(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockuseCase)(nil).Create), ctx, dto)
}

// CreateImages mocks base method.
func (m *MockuseCase) CreateImages(ctx context.Context, dto advertusecase.CreateImagesDTO) ([]advertentity.AdvertImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateImages", ctx, dto)
	ret0, _ := ret[0].([]advertentity.AdvertImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateImages indicates an expected call of CreateImages.
func (mr *MockuseCaseMockRecorder) CreateImages(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateImages", reflect.TypeOf((*MockuseCase)(nil).CreateImages), ctx, dto)
}

// Delete mocks base method.
func (m *MockuseCase) Delete(ctx context.Context, dto advertusecase.DeleteDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockuseCaseMockRecorder) Delete(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockuseCase)(nil).Delete), ctx, dto)
}

// DeleteImage mocks base method.
func (m *MockuseCase) DeleteImage(ctx context.Context, dto advertusecase.DeleteImageDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockuseCaseMockRecorder) DeleteImage(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockuseCase)(nil).DeleteImage), ctx, dto)
}

// GetByID mocks base method.
func (m *MockuseCase) GetByID(ctx context.Context, dto advertusecase.GetByIDDTO) (advertentity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, dto)
	ret0, _ := ret[0].(advertentity.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockuseCaseMockRecorder) GetByID(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockuseCase)(nil).GetByID), ctx, dto)
}

// GetImageByID mocks base method.
func (m *MockuseCase) GetImageByID(ctx context.Context, dto advertusecase.GetImageDTO) (io.ReadCloser, advertentity.AdvertImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImageByID", ctx, dto)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(advertentity.AdvertImage)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetImageByID indicates an expected call of GetImageByID.
func (mr *MockuseCaseMockRecorder) GetImageByID(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImageByID", reflect.TypeOf((*MockuseCase)(nil).GetImageByID), ctx, dto)
}

// List mocks base method.
func (m *MockuseCase) List(ctx context.Context, dto advertusecase.ListDTO) (int64, []advertentity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, dto)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].([]advertentity.Advert)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockuseCaseMockRecorder) List(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockuseCase)(nil).List), ctx, dto)
}

// ListFavourites mocks base method.
func (m *MockuseCase) ListFavourites(ctx context.Context, dto advertusecase.ListDTO) (int64, []advertentity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFavourites", ctx, dto)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].([]advertentity.Advert)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFavourites indicates an expected call of ListFavourites.
func (mr *MockuseCaseMockRecorder) ListFavourites(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFavourites", reflect.TypeOf((*MockuseCase)(nil).ListFavourites), ctx, dto)
}

// Patch mocks base method.
func (m *MockuseCase) Patch(ctx context.Context, dto advertusecase.PatchDTO) (advertentity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", ctx, dto)
	ret0, _ := ret[0].(advertentity.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockuseCaseMockRecorder) Patch(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockuseCase)(nil).Patch), ctx, dto)
}

// Reject mocks base method.
func (m *MockuseCase) Reject(ctx context.Context, id int64) (advertentity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reject", ctx, id)
	ret0, _ := ret[0].(advertentity.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reject indicates an expected call of Reject.
func (mr *MockuseCaseMockRecorder) Reject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reject", reflect.TypeOf((*MockuseCase)(nil).Reject), ctx, id)
}
